name: flutterapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.7.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/animal_kingdom.gif
    - assets/images/thanks.gif
    - assets/images/antilope.gif
    - assets/images/bat.gif
    - assets/images/bear.gif
    - assets/images/bee.gif
    - assets/images/camel.gif
    - assets/images/canary.gif
    - assets/images/cat.gif
    - assets/images/chicken.gif
    - assets/images/cow.gif
    - assets/images/crab.gif
    - assets/images/deer.gif
    - assets/images/dog.gif
    - assets/images/dolphin.gif
    - assets/images/donkey.gif
    - assets/images/duck.gif
    - assets/images/eagle.gif
    - assets/images/elephant.gif
    - assets/images/fly.gif
    - assets/images/frog.gif
    - assets/images/giraffe.gif
    - assets/images/horse.gif
    - assets/images/insect.gif
    - assets/images/kangaroo.gif
    - assets/images/lion.gif
    - assets/images/monkey.gif
    - assets/images/mouse.gif
    - assets/images/owl.gif
    - assets/images/pig.gif
    - assets/images/pigeon.gif
    - assets/images/rabbit.gif
    - assets/images/scorpion.gif
    - assets/images/sea_serpent.gif
    - assets/images/shark.gif
    - assets/images/sheep.gif
    - assets/images/shrimp.gif
    - assets/images/snake.gif
    - assets/images/tiger.gif
    - assets/images/whale.gif
    - assets/images/worm.gif
    - assets/images/zebra.gif
    - assets/sounds/animal_kingdom.mp3
    - assets/sounds/thanks.mp3
    - assets/sounds/contribution.mp3
    - assets/sounds/reject.mp3
    - assets/sounds/correct.mp3
    - assets/sounds/oh_no.mp3
    - assets/sounds/animal_kingdom_1.mp3
    - assets/sounds/antilope.mp3
    - assets/sounds/bat.mp3
    - assets/sounds/bear.mp3
    - assets/sounds/bee.mp3
    - assets/sounds/camel.mp3
    - assets/sounds/canary.mp3
    - assets/sounds/cat.mp3
    - assets/sounds/chicken.mp3
    - assets/sounds/cow.mp3
    - assets/sounds/crab.mp3
    - assets/sounds/deer.mp3
    - assets/sounds/dog.mp3
    - assets/sounds/dolphin.mp3
    - assets/sounds/donkey.mp3
    - assets/sounds/duck.mp3
    - assets/sounds/eagle.mp3
    - assets/sounds/elephant.mp3
    - assets/sounds/fly.mp3
    - assets/sounds/frog.mp3
    - assets/sounds/giraffe.mp3
    - assets/sounds/horse.mp3
    - assets/sounds/insect.mp3
    - assets/sounds/kangaroo.mp3
    - assets/sounds/lion.mp3
    - assets/sounds/monkey.mp3
    - assets/sounds/mouse.mp3
    - assets/sounds/owl.mp3
    - assets/sounds/pig.mp3
    - assets/sounds/pigeon.mp3
    - assets/sounds/rabbit.mp3
    - assets/sounds/scorpion.mp3
    - assets/sounds/sea_serpent.mp3
    - assets/sounds/shark.mp3
    - assets/sounds/sheep.mp3
    - assets/sounds/snake.mp3
    - assets/sounds/tiger.mp3
    - assets/sounds/whale.mp3
    - assets/sounds/worm.mp3
    - assets/sounds/zebra.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
